travis:
  secure:
    BINSTAR_TOKEN: tnuAYh8UWAtgFLFFxHTQV8NenA90/nM5jMEavxwZhFaehEVopE0J7JqLVqSzWDX69uS7KEZIyX6oTgIwn6OuyXIBwASLQ52aou4jaCZsQDAOjU4hlRR1xdHrX1kvjz1o3CIpfOj+By6mdsIT9vZLc/Ro7QNe1Z6tbAqB5z1oHyUI0px8i5rTmb3WpRlJwl9ucSQNT41nkw47CUnKIKpg6hgzvPa0CXw+Zx37kaWaJlZTwmy+JXXLGylApkK8C0Laly9JEs/zLodzZ/IntYtyTvLT+UGpRQiF+UwMtYsf7Fvy27CEVTZyXpar0Q+LyIS76RJqn2rBs2+pFw8/gaytN77dAS+NvepMG5xIGZfAkynquQqvVuCk3WR7vjPkQALIlh7pk+P3uMqHHwX/A+AwbZeMIx/DeWLAAd8PwOSEq9F19lQ98y6m7jPURDMPCUtw/qHniZic+NF5wPsiSxtFnkUtX0AXfyfye68RVarc+Lfuh5scm6U2RRkrUzrVA+DFuETGQiP76MGtMx0jeuXGRcy5DHGKMcPMlle4PDtYd1Z4h0w+IPtvlabDL7h+clC+OdCzMUwdIdKvaUXAMYtIsyfjMk9ny4t28RDvDNWT7Q9ixGLi3ISRDsyhlWQgyd7uLPDLj0ws5gGT4fuWvqkqnvE9YH+z6p0PPmAY/ZPMAJc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
