travis:
  secure:
    BINSTAR_TOKEN: eJVT6TfmnHbm/pqvDTQMcZxbfBxbnTgev9mwjFqD1SpQEYeA6GkM4oN/O+dRV78h9SbhBQ/unUfn6h9GsTi6VI5PHRKLtGH32oASHmLOY3HoLZubx0wJOUMAvw3XNez9cn2mAJRmkj56F1/niBnX4eOvIJ816YnC+xEzuQjOoELYETRgh3W19Yi0IrLcq1lBE39079VRLRKHMfXGL+KsDfe7bHY8BecRl2r9rIZHHjrQ03TdbucovIBm632I6NQj0aaskme0bWUvFOYgA16ohaeIKSjPUFGHyHm/DwHeZquSzr9pr4FWA6sol/JGCmqMVxgR9Z/vsHdqCzzQ05TglhdOaiCCGuvYRM/7BnWV4pRTJ3iT22ztpeXmQK2nyl0NUboEsSLn+q2n3gHew944w94vGvGmQlTSRWCDhy7HH7PNAscs6lk+3s53PMiDwRF7cgNSBYouPPvcBv3xw5gF9oB0w06dxf6MtmDT+t/JHS/leP0qcTv2Pn+1aY9I6v+gcWsphphR5MCXrZB1Q7m9AUuQO4VPSmqg6PtvbIKDMPx/Sts9natix5bEBxs4p6Ql4xRx6Js2yRxcotafuXoGErYXhKinA6+q2CL7HkPuTrjkK5HGYNmSE8rFJk9Dzz5+pfsQ5P6YAoYyUlP9tG+hYZ/LvaIagI7QKnhI6YeUEJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
